EDF-3773 SAK-48952 - Grader: Missing ES strings. (#11657)
mpellicer/sakai-apereo pull request #15
Opened 2023-09-22 12:16 UTC by V100X

2023-09-22 12:18 UTC, mpellicer commented on webcomponents/bundle/src/main/bundle/grader_es.properties
> +filter_settings_warning=Has aplicado cambios. Haz clic en el icono de la rueda para verlos.
He actualizado esto recientemente, usa 'del engranaje' en lugar 'de la rueda'.
https://github.com/sakaiproject/sakai/pull/11929

2023-09-22 12:20 UTC, mpellicer requested changes
Cambio de cadena.

2023-09-22 12:25 UTC, V100X commented
Ready

2023-09-25 05:48 UTC, merged

2023-09-25 05:48 UTC, mpellicer commented
Gracias Vicent, lanza las comunicaciones que sean necesarias enlazando a los commits apropiados.